### ISSUE TITLE
Crash while evaluating "2+2+2" expression

### ISSUE THREAD

**Issue by Erelwar** [Solant/QExpression#1]
In `QExpression::toReversePolishNotation()` . Needs to add something like: `if(stack.isEmpty()) { break; }` after `qexpression.cpp:125`.

**Comment by Solant** [comment]
Hi

Thanks for a fix, did it in https://github.com/Solant/QExpression/commit/3bb731fe6c186b186edd9c9dc518855c52ddd625

**Comment by Erelwar** [comment]
Sorry, my mistake - expression which was causing an error is "2*2+2".

**Comment by Solant** [comment]
That's fine, I had the same issue with `2+2+2`, so `2*2+2` should be also fixed

**Comment by Erelwar** [comment]
Thanks for incredibly fast answer! Good luck!
